name-template: "v$RESOLVED_VERSION 🔒"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "enhancement"
  default: patch
categories:
  - title: "⚠️ Breaking changes"
    label: "breaking-change"
  - title: "🚀 Enhancements"
    label: "enhancement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🔒 Security"
    label: "security"
  - title: "⚙️ Maintenance/misc"
    label:
      - "maintenance"
      - "documentation"
template: |
  ## What's Changed in v1.x

  This is a maintenance release for the v1.x series. For the latest features and improvements, please consider upgrading to v2.x.

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  Thanks to all contributors! 🎉
  $CONTRIBUTORS
no-changes-template: "Changes are coming soon 😎"
sort-direction: "ascending"
replacers:
  - search: '/(?:and )?@dependabot-preview(?:\[bot\])?,?/g'
    replace: ""
  - search: '/(?:and )?@meili-bors(?:\[bot\])?,?/g'
    replace: ""
  - search: "/(?:and )?@meili-bot,?/g"
    replace: ""
  - search: '/(?:and )?@dependabot(?:\[bot\])?,?/g'
    replace: ""
