version: 1
update_configs:
    - package_manager: "php:composer"
      directory: "/"
      update_schedule: "live"
      default_labels:
          - "depbump"
      commit_message:
          prefix: "[bump-version]"
