<?php

declare(strict_types=1);

namespace Meilisearch\Contracts;

final class CreateKeyQuery
{
    /**
     * @param list<KeyAction>         $actions     a list of actions permitted for the key
     * @param list<non-empty-string>  $indexes     A list of accessible indexes permitted for the key. ["*"] for all
     *                                             indexes. The * character can be used as a wildcard when located at
     *                                             the last position. e.g. products_* to allow access to all indexes
     *                                             whose names start with products_.
     * @param non-empty-string|null   $name        A human-readable name for the key. null if empty.
     * @param non-empty-string|null   $description A description for the key. null if empty.
     * @param non-empty-string|null   $uid         A uuid v4 to identify the API Key. If not specified, it's generated by Meilisearch.
     * @param \DateTimeImmutable|null $expiresAt   Represent the expiration date and time as RFC 3339 format. null equals to no expiration time.
     */
    public function __construct(
        private readonly array $actions,
        private readonly array $indexes,
        private readonly ?string $name = null,
        private readonly ?string $description = null,
        private readonly ?string $uid = null,
        private readonly ?\DateTimeImmutable $expiresAt = null,
    ) {
    }

    /**
     * @return array{
     *     actions: list<non-empty-string>,
     *     indexes: list<non-empty-string>,
     *     description: non-empty-string|null,
     *     name: non-empty-string|null,
     *     expiresAt: non-empty-string|null,
     *     uid?: non-empty-string
     * }
     */
    public function toArray(): array
    {
        $payload = [
            'actions' => array_column($this->actions, 'value'),
            'indexes' => $this->indexes,
            'description' => $this->description,
            'name' => $this->name,
            'expiresAt' => $this->expiresAt?->format('Y-m-d\TH:i:s.vu\Z'),
        ];
        if (null !== $this->uid) {
            $payload['uid'] = $this->uid;
        }

        return $payload;
    }
}
